Traceback (most recent call last):
  File "/Users/godfreybeddard/Library/Python/3.8/lib/python/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/godfreybeddard/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/godfreybeddard/Library/Python/3.8/lib/python/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/godfreybeddard/Library/Python/3.8/lib/python/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/godfreybeddard/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/godfreybeddard/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/godfreybeddard/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Algorithm 12

dataname='1TIM.pdb'

numA =  36                    # residue 36
numB =  numA+1                # residue B 
numC =  numA-1
chain= 'B'                   # which chain ?                   

resA = np.zeros((14,3),dtype=float)        # as largest residiue trp has 14 atoms, 3 for x,y,z
resB = np.zeros((14,3),dtype=float)
resC = np.zeros((14,3),dtype=float)
with open(dataname) as f:
    kA = 0                                 # counter for index in list resA etc.
    kB = 0
    kC = 0
    for line in f:
        new_str=' '.join(line.split())  
        vals = new_str.split(' ')
        if vals[0] == 'ATOM':
            if vals[5] == str(numA) and vals[4] == chain:
                resA[kA][:] = [vals[6],vals[7],vals[8]]
                kA = kA + 1
            if vals[5] == str(numB) and vals[4] == chain:
                resB[kB][:] = [vals[6],vals[7],vals[8]]
                kB = kB + 1
            if vals[5] == str(numC) and vals[4] == chain:
                resC[kC][:] = [vals[6],vals[7],vals[8]]
                kC = kC + 1
f.close()

print('{:s}{:6.3f}'.format('torsion angle = ',torsion_angle(resA[0],resA[1],resA[2],resB[0]) ) )
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/var/folders/gn/whk4pp2x4kz_ftg0b1ycmh340000gn/T/ipykernel_13964/3027024868.py[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m [0mresB[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mzeros[0m[0;34m([0m[0;34m([0m[0;36m14[0m[0;34m,[0m[0;36m3[0m[0;34m)[0m[0;34m,[0m[0mdtype[0m[0;34m=[0m[0mfloat[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0mresC[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mzeros[0m[0;34m([0m[0;34m([0m[0;36m14[0m[0;34m,[0m[0;36m3[0m[0;34m)[0m[0;34m,[0m[0mdtype[0m[0;34m=[0m[0mfloat[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 13[0;31m [0;32mwith[0m [0mopen[0m[0;34m([0m[0mdataname[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m     [0mkA[0m [0;34m=[0m [0;36m0[0m                                 [0;31m# counter for index in list resA etc.[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m     [0mkB[0m [0;34m=[0m [0;36m0[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '1TIM.pdb'
FileNotFoundError: [Errno 2] No such file or directory: '1TIM.pdb'

